name: CI

on:
  push:
    branches: [main, dev]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: ["3.12"] # test on multiple Python versions

    steps:
      - name: Checkout ParallelKDEpy
        uses: actions/checkout@v6

      # 2️⃣ Setup Python
      - name: Setup Python ${{ matrix.python-version }}
        uses: actions/setup-python@v6
        with:
          python-version: ${{ matrix.python-version }}

      # 3️⃣ Install your package via Poetry
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install poetry
          poetry config virtualenvs.create false  # install into the runner’s env
          poetry install --no-interaction --no-ansi
          pip install pytest pytest-cov

      # 5️⃣ Run tests
      - name: Run pytest
        run: |
          pytest

      # 6️⃣ Upload coverage
      - name: Upload HTML coverage report
        uses: actions/upload-artifact@v5
        with:
          name: coverage-html
          path: htmlcov

      - name: Upload coverage report XML
        uses: actions/upload-artifact@v5
        with:
          name: coverage-xml
          path: coverage.xml
